# Site settings
title: "Charles Sanquer"
email: charles.sanquer.pro@gmail.com
description: "Charles Sanquer Blog"
baseurl: ""
url: "http://www.charles-sanquer.net/"
title_description: "Agilist and DevOps enthousiast"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
timezone: Europe/Paris
encoding: utf-8
google_analytics: ""
disqus_account: csanquer
github_repository:
addthis_id:
post_limit: 5

# Social usernames/URLs
github_username:  csanquer
twitter_username: CSanquer
linkedin_link: https://www.linkedin.com/in/charlessanquer
google_plus_link:
stackoverflow_link:

# Footer
footer_left: ""
footer_right: ""
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude:
  - vendor
  - curriculum-vitae.md
  - projects.md
